/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cv_hy_picoincamera_PicoHelper */

#ifndef _Included_com_cv_hy_picoincamera_PicoHelper
#define _Included_com_cv_hy_picoincamera_PicoHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cv_hy_picoincamera_PicoHelper
 * Method:    detect
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_cv_hy_picoincamera_PicoHelper_detect
  (JNIEnv *, jclass, jlong, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
